### PR TITLE
#160011180  Create articles

### PR DESCRIPTION
**Pull request by migot01**
#### What does this PR do?
Implement create article

#### Description of tasks to be completed
Create article

#### How should this be manually tested?
```sh
$ git clone https://github.com/andela/ah-titans-frontend.git
```
```sh
$ git checkout -b ft-create-articles-160011180
```
```sh
$ cd ah-titans-frontend
```

> Install the dependencies with the command below.

```sh
$ npm install
```
>Then run the app with the command below.
```sh
$ npm start
```
>Now you can navigate to your browser and you should be able to see a page as the one shown on the screenshot below.

### screenshots

Login to the app to view the red add button and click on it to go to the create article page

image

-Then you will see the create article form as shown below

image

image

image

#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160011180](https://www.pivotaltracker.com/story/show/160011180)

### CODE REVIEW

**Review by johnmusiu — CHANGES_REQUESTED** [review]
I checked out to your branch and on clicking `new` it loads the create article form. On clicking submit it goes into `PUBLISHING` then no error message pops up. I suppose you should display an error message (that is visible from the console) or protect the create article route from access without being logged in.

**Review by janetnim — COMMENTED** [review]
While testing your feature i find that I cannot be able to publish a post and console message shows "undefined"

**Comment by dcDalin** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  :exclamation: Big PR
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by migot01** [comment]
@johnmusiu  @janetnim We have implemented the requested changed ,please take another look at it

**Review by johnmusiu — APPROVED** [review]
Looks good now

**Review by janetnim — APPROVED** [review]

**Pull request merged**
