### PR TITLE
#160011174 Run codeclimate test coverage

### PR DESCRIPTION
**Pull request by dcDalin**
#### What does this PR do?
Sets up CodeClimate 
Runs CodeClimate test coverage after passing the tests from CircleCI

#### How should this be manually tested?
View the following links:
> [Circle CI Link](https://circleci.com/gh/andela/ah-titans-frontend/8)
> [Code Climate Link](https://codeclimate.com/github/andela/ah-titans-frontend)
#### Any background context you want to provide?
No

#### What are the relevant Pivotal Tracker Stories?
[#160011174](https://www.pivotaltracker.com/story/show/160011174)

### CODE REVIEW

**Comment by jmnyarega** [comment]
Please remove circleci configurations.

**Comment by dcDalin** [comment]
@jmnyarega 

Pivotal Tracker story describes that I need to run CodeClimate test coverage after passing the tests from CircleCi. I will, therefore, need the configurations as this is what is passing the test results back to CodeClimate. Kindly elaborate your suggestion for removing CircleCI configurations.

**Comment by jmnyarega** [comment]
Seen it, since travis and circleci are doing the same thing, `running our tests`, we don't need all of them. Let's just use travis

**Comment by dcDalin** [comment]
@jmnyarega Yes, we can do with one Continuous Integration.

**Comment by jmnyarega** [comment]
@dcDalin let's get remove travis-ci

**Pull request merged**
